stages:
  - install
  - build

install_dependencies:
  stage: install
  script:
    - echo "Installing all dependencies"
    - npm install

build_app:
  stage: build
  script:
    - echo "Building Next.js app"
    - npm run build
